# Mod properties
mod_id=justtrialspawners
mod_version=1.2.2
mod_group=com.breakinblocks.justtrialspawners

# Minecraft/Forge
minecraft_version=1.20.1
forge_version=47.4.0

# Java
java_version=17

# Gradle JVM settings
org.gradle.jvmargs=-Xmx512m -XX:MaxMetaspaceSize=256m -XX:ReservedCodeCacheSize=128m -XX:+UseSerialGC
